### ISSUE TITLE
DatePickerInput: add possibility to open/close the calendar by clicking the icon

### ISSUE THREAD

**Issue by drebrez** [neolution-ch/react-hook-form-components#73]

**Comment by manni497** [comment]
@neotrow We have this in our solution but we are not able to reproduce the behaviour externally with package DatePickerInput as we need to access the ref on the DatePicker and not on the internal Input and this would be a breaking change. Let's hear your opinion. We can discuss it if you want :D

**Comment by neotrow** [comment]
Can you post the code you have in your solution?

**Comment by neotrow** [comment]
Thanks @manni497 

I think it should be easy to extend the current solution without introducing braking changes:

1. Add a property to `DatePickerInputProps`
`datePickerRef?: React.MutableRefObject<DatePicker<any, undefined> | null>;`

2. Assign the ref in the current ref callback:

```
  ref={(elem) => {
   ...
   elem && field.ref((elem as any).input);
   if (props.datePickerRef) {
      props.datePickerRef.current = elem;
   }
}}
```

3. In your solution to the following:
`const datePickerRef = useRef<DatePicker | null>(null);` 

and pass it to the component:

```
<DatePickerInput datePickerRef={datePickerRef} ..... />
```



I haven't tested it but I think that should work. Let me know how it goes :-)

**Comment by manni497** [comment]
@neotrow Yes, I didn't think to the callback assignment :D You are right...  think we will need an Id also in the formGroup for the clickOutsideLogic, but let's try :D

**Comment by severinoAmmirati** [comment]
Solution suggested by @neotrow works, and implemented here 
https://github.com/neolution-ch/react-hook-form-components/pull/75

**Comment by neotrow** [comment]
Added in version 1.6.0: https://github.com/neolution-ch/react-hook-form-components/releases/tag/1.6.0

Thanks @severinoAmmirati  for the PR
